test-anagram:
  image: golang:1.17
  script:
    - make test-anagram
  only:
    changes:
      - anagram/*

test-brokennode:
  image: golang:1.17
  script:
    - make test-brokennode
  only:
    changes:
      - brokennode/*


test-buildword:
  image: golang:1.17
  script:
    - make test-buildword
  only:
    changes:
      - buildword/*


test-chess:
  image: golang:1.17
  script:
    - make test-chess
  only:
    changes:
      - chess/*


test-coins:
  image: golang:1.17
  script:
    - make test-coins
  only:
    changes:
      - coins/*


test-floyd:
  image: golang:1.17
  script:
    - make test-floyd
  only:
    changes:
      - floyd/*


test-functionfrequency:
  image: golang:1.17
  script:
    - make test-functionfrequency
  only:
    changes:
      - functionfrequency/*


test-jaro:
  image: golang:1.17
  script:
    - make test-jaro
  only:
    changes:
      - jaro/*


test-lastlettergame:
  image: golang:1.17
  script:
    - make test-lastlettergame
  only:
    changes:
      - lastlettergame/*


test-mergesort:
  image: golang:1.17
  script:
    - make test-mergesort
  only:
    changes:
      - mergesort/*


test-missingnumbers:
  image: golang:1.17
  script:
    - make test-missingnumbers
  only:
    changes:
      - missingnumbers/*


test-node-degree:
  image: golang:1.17
  script:
    - make test-node-degree
  only:
    changes:
      - node_degree/*


test-reverseparentheses:
  image: golang:1.17
  script:
    - make test-reverseparentheses
  only:
    changes:
      - reverseparentheses/*


test-romannumerals:
  image: golang:1.17
  script:
    - make test-romannumerals
  only:
    changes:
      - romannumerals/*


test-secretmessage:
  image: golang:1.17
  script:
    - make test-secretmessage
  only:
    changes:
      - secretmessage/*


test-shorthash:
  image: golang:1.17
  script:
    - make test-shorthash
  only:
    changes:
      - shorthash/*


test-snowflakes:
  image: golang:1.17
  script:
    - make test-snowflakes
  only:
    changes:
      - snowflakes/*

test-sumdecimal:
  image: golang:1.17
  script:
    - make test-sumdecimal
  only:
    changes:
      - sumdecimal/*


test-warriors:
  image: golang:1.17
  script:
    - make test-warriors
  only:
    changes:
      - warriors/*

test-wordladder:
  image: golang:1.17
  script:
    - make test-wordladder
  only:
    changes:
      - wordladder/*

test-all:
  image: golang:1.17
  script:
    - make test



